# Generated by Django 5.2.6 on 2025-09-08 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Company name', max_length=200)),
                ('symbol', models.CharField(help_text='Stock symbol', max_length=10, unique=True)),
                ('description', models.TextField(help_text='Company description')),
                ('industry', models.CharField(help_text='Industry sector', max_length=100)),
                ('founded_year', models.IntegerField(blank=True, help_text='Year company was founded', null=True)),
                ('headquarters', models.CharField(help_text='Headquarters location', max_length=200)),
                ('website', models.URLField(blank=True, help_text='Company website')),
                ('ceo', models.CharField(blank=True, help_text='CEO name', max_length=100)),
                ('employees', models.IntegerField(blank=True, help_text='Number of employees', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_fy1', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue FY-1', max_digits=12, null=True)),
                ('revenue_fy2', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue FY-2', max_digits=12, null=True)),
                ('revenue_fy3', models.DecimalField(blank=True, decimal_places=2, help_text='Revenue FY-3', max_digits=12, null=True)),
                ('profit_fy1', models.DecimalField(blank=True, decimal_places=2, help_text='Net profit FY-1', max_digits=12, null=True)),
                ('profit_fy2', models.DecimalField(blank=True, decimal_places=2, help_text='Net profit FY-2', max_digits=12, null=True)),
                ('profit_fy3', models.DecimalField(blank=True, decimal_places=2, help_text='Net profit FY-3', max_digits=12, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=2, help_text='Price to Earnings ratio', max_digits=6, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, help_text='Return on Equity (%)', max_digits=5, null=True)),
                ('debt_to_equity', models.DecimalField(blank=True, decimal_places=2, help_text='Debt to Equity ratio', max_digits=5, null=True)),
                ('book_value_per_share', models.DecimalField(blank=True, decimal_places=2, help_text='Book value per share', max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='ipo_app.company')),
            ],
            options={
                'verbose_name': 'Financial Metrics',
                'verbose_name_plural': 'Financial Metrics',
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20)),
                ('exchange', models.CharField(choices=[('NSE', 'National Stock Exchange'), ('BSE', 'Bombay Stock Exchange'), ('BOTH', 'Both NSE & BSE')], default='BOTH', max_length=10)),
                ('price_band_min', models.DecimalField(decimal_places=2, help_text='Minimum price per share', max_digits=10)),
                ('price_band_max', models.DecimalField(decimal_places=2, help_text='Maximum price per share', max_digits=10)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Final listing price', max_digits=10, null=True)),
                ('open_date', models.DateField(help_text='IPO opening date')),
                ('close_date', models.DateField(help_text='IPO closing date')),
                ('listing_date', models.DateField(blank=True, help_text='Stock listing date', null=True)),
                ('total_shares', models.BigIntegerField(help_text='Total number of shares offered')),
                ('lot_size', models.IntegerField(default=1, help_text='Minimum number of shares to apply')),
                ('issue_size', models.DecimalField(decimal_places=2, help_text='Total issue size in crores', max_digits=15)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, help_text='Market cap at upper price band', max_digits=15, null=True)),
                ('subscription_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Subscription rate (times)', max_digits=5, null=True)),
                ('listing_gains', models.DecimalField(blank=True, decimal_places=2, help_text='Listing gains percentage', max_digits=5, null=True)),
                ('lead_managers', models.TextField(help_text='Lead managers/underwriters')),
                ('registrar', models.CharField(blank=True, help_text='Registrar name', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_app.company')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='IPONews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News headline', max_length=300)),
                ('content', models.TextField(help_text='News content')),
                ('source', models.CharField(help_text='News source', max_length=100)),
                ('published_date', models.DateTimeField(help_text='Publication date')),
                ('url', models.URLField(blank=True, help_text='Source URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='ipo_app.ipo')),
            ],
            options={
                'verbose_name': 'IPO News',
                'verbose_name_plural': 'IPO News',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_subscription', models.DecimalField(blank=True, decimal_places=2, help_text='Retail subscription (times)', max_digits=5, null=True)),
                ('hni_subscription', models.DecimalField(blank=True, decimal_places=2, help_text='HNI subscription (times)', max_digits=5, null=True)),
                ('institutional_subscription', models.DecimalField(blank=True, decimal_places=2, help_text='Institutional subscription (times)', max_digits=5, null=True)),
                ('grey_market_premium', models.DecimalField(blank=True, decimal_places=2, help_text='Grey market premium', max_digits=8, null=True)),
                ('analyst_rating', models.CharField(blank=True, choices=[('strong_buy', 'Strong Buy'), ('buy', 'Buy'), ('hold', 'Hold'), ('avoid', 'Avoid')], max_length=20, null=True)),
                ('risk_score', models.IntegerField(blank=True, help_text='Risk score (1-10, where 10 is highest risk)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('application_count', models.BigIntegerField(blank=True, help_text='Total applications received', null=True)),
                ('amount_collected', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount collected (crores)', max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_data', to='ipo_app.ipo')),
            ],
            options={
                'verbose_name': 'Market Data',
                'verbose_name_plural': 'Market Data',
            },
        ),
    ]
